In [2]:
import pandas as pd
import numpy as np

### loading data

In [3]:
df = pd.read_csv("cardio_train.csv")

### check data

In [4]:
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

### inspect data

In [5]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,19468.865814,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,2467.251667,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,10798.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,17664.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,19703.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,21327.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

### missing value

In [6]:
df.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

### duplicates

In [8]:
df = df.drop_duplicates()

In [9]:
df.shape

(70000, 13)

### Convert Age to Years

In [10]:
df["age_years"] = (df["age"] / 365).round(0)

### Create BMI Column

In [11]:
df["BMI"] = (df["weight"] / ((df["height"]/100)**2)).round(1)

### Create Age Groups

In [12]:
bins = [0,40,50,60,100]
labels = ["<40","40-50","50-60","60+"]

df["age_group"] = pd.cut(df["age_years"], bins=bins, labels=labels)

### Check Blood Pressure Outliers

In [13]:
df[(df["ap_hi"] < 80) | (df["ap_hi"] > 250)]
df[(df["ap_lo"] < 40) | (df["ap_lo"] > 150)]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,BMI,age_group
228,314,17489,2,183,98.0,160,1100,1,2,1,0,1,1,48.0,29.3,40-50
241,334,21932,2,157,60.0,160,1000,2,1,0,0,0,1,60.0,24.3,50-60
260,357,18217,1,150,83.0,140,800,1,1,0,0,1,1,50.0,36.9,40-50
329,458,23407,1,176,63.0,160,1000,2,2,0,0,0,1,64.0,20.3,60+
345,482,18704,1,154,81.0,140,1000,2,1,0,0,1,1,51.0,34.2,50-60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69771,99659,23330,1,167,81.0,160,1000,1,1,0,0,1,1,64.0,29.0,60+
69872,99798,21808,1,152,56.0,160,1000,1,1,0,0,1,1,60.0,24.2,50-60
69878,99807,21239,2,168,95.0,160,1000,1,1,0,0,1,1,58.0,33.7,50-60
69885,99816,22417,2,166,78.0,170,1000,1,1,0,0,0,0,61.0,28.3,60+
69967,99955,21416,2,168,63.0,140,1000,1,1,0,0,1,1,59.0,22.3,50-60

In [15]:
df = df[(df["ap_hi"] < 250) & (df["ap_hi"] > 80)]
df = df[(df["ap_lo"] < 150) & (df["ap_lo"] > 40)]

In [16]:
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,BMI,age_group
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0,50.0,22.0,40-50
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1,55.0,34.9,50-60
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1,52.0,23.5,50-60
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1,48.0,28.7,40-50
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0,48.0,23.0,40-50

In [17]:
df.shape

(68615, 16)

In [18]:
df.to_csv("cleaned_cardio_data.csv", index=False)